### Inicio de sesión administrador
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "usuario": "admin",
    "contraseña": "admin"
}

###

### Inicio de sesión profesor
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "usuario": "mgonzalez",
    "contraseña": "clave123"
}

###

### Cerrar sesión
POST http://localhost:3000/api/logout HTTP/1.1
Content-Type: application/json