### Crear inscripcion de cliente
POST http://localhost:3000/api/clientes/1/inscripciones HTTP/1.1
Content-Type: application/json

{
    "idProfesor": 1,
    "idCliente": 1,
    "idPase": 1,
    "diaInicio": "01-10-2025",
    "diaFin": "01-11-2025",
    "precio": 8000,
    "estado": "A"
}